version: '3.8'

services:
  samba-ldap-webmin:
    build: .
    container_name: samba-ldap-webmin
    ports:
      - "88:88/udp"
      - "88:88/tcp"
      - "135:135/tcp"
      - "139:139/tcp"
      - "445:445/tcp"
      - "464:464/tcp"
      - "464:464/udp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"
      - "10000:10000/tcp"
    volumes:
      - samba-data:/srv/samba/shared
      - ./smb.conf:/etc/samba/smb.conf  # Mount the smb.conf file
    environment:
      - WEBMIN_PASSWORD=password
    dns:
      - 8.8.8.8
    depends_on:
      - openldap

  openldap-server:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap-data:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    networks:
      - samba-ldap-network

volumes:
  samba-data:
  openldap-data:
  openldap-config:

networks:
  samba-ldap-network:
    driver: bridge
